In [3]:
import numpy as np
x=np.array([45,67,57,60])
print(x)
print(type(x))
print(x.dtype)

[45 67 57 60]
<class 'numpy.ndarray'>
int32


In [7]:
a2=np.array([[20,40],[30,60]])
print(a2)
print(type(a2))
print(a2.dtype)

[[20 40]
 [30 60]]
<class 'numpy.ndarray'>
int32


In [13]:
#reshaping an array using reshape()
a=np.array([10,20,30,40])
b=a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [17]:
#create an array with arrange()
c=np.arange(3,10)
print(c)
type(c)

[3 4 5 6 7 8 9]


numpy.ndarray

In [21]:
#use of np.sqrt()
d=np.array([9,20,30,40,0])
print(d)
print(np.around(np.sqrt(d),2))

[ 9 20 30 40  0]
[3.   4.47 5.48 6.32 0.  ]


In [31]:
a1=np.array([[3,4,5,8],[7,2,8,np.NaN]])
print(a1)
a1.dtype

[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]


dtype('float64')

In [37]:
#mathematical operations on rows n columns
a2=np.array([[3,4,5],[4,5,6],[3,4,5]])
a2.sum(axis=1)

array([12, 15, 12])

In [43]:
a3=np.array([[3,4,5],[4,5,6],[3,4,5]])
print(a3)
print()
np.fill_diagonal(a3,0)
print(a3)

[[3 4 5]
 [4 5 6]
 [3 4 5]]

[[0 4 5]
 [4 0 6]
 [3 4 0]]


In [45]:
#transpose of matrices
print(a2.T)

[[3 4 3]
 [4 5 4]
 [5 6 5]]


In [51]:
#multiplying
c=np.matmul(a2,a3)
c

array([[31, 32, 39],
       [38, 40, 50],
       [31, 32, 39]])

In [53]:
#accessing the array elements
a4=np.array([[2,3,4],[4,5,6],[7,8,9],[9,0,1]])
a4

array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9],
       [9, 0, 1]])

In [67]:
a4[2,2]

9

In [ ]:
print(np.amax(a3, axis =1))
print(np.amax(a3,axis =0))